linters:
  # Enable all available linters.
  # Default: false
  enable-all: true

  # Enable only fast linters from enabled linters set (first run won't be fast)
  # Default: false
  fast: false

  disable:
    - depguard
    - exportloopref
    - forbidigo
    - exhaustruct
    - godox
    - funlen
linters-settings:
  tagalign:
    align: false
    sort: false
    order:
      - json
      - yaml
      - yml
      - toml
      - mapstructure
      - binding
      - validate
